services:
  - type: web
    name: tribike
    env: docker
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: tribike_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: tribike_db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: tribike_db
          property: database
      - key: DB_USER
        fromDatabase:
          name: tribike_db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: tribike_db
          property: password
databases:
  - name: tribike_db
    plan: free
